### ISSUE TITLE
Bug: There are issues for inspector when enable replicaiton for harbor and do not set namespace selector for policy

### ISSUE THREAD

**Issue by JingChen23** [vmware-tanzu/cloud-native-security-inspector#84]
**Environment**
Platform: Self-built K8s
Kubernetes/Platform Version(s): 1.21.3

**Describe the bug**

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 246 [running]:
github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/core.ArtifactID.Namespace({{0xc00081fa40?, 0xc0001bf400?}, {0xc0008035c8?, 0x4e729f?}})
	/workspace/pkg/data/core/types.go:92 +0x1ce
github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/providers/harbor.(*Adapter).Read(0xc00086e330, {0x249b4b8, 0xc00071d880}, {{0xc00081fa40?, 0x9?}, {0xc0008035c8?, 0x13?}}, {0xc0002a6210, 0x1, 0x1})
	/workspace/pkg/data/providers/harbor/adapter.go:89 +0x1a5
github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection.(*controller).Run.func1.1({{{0xc00064c120, 0xa}, {0xc0008032f0, 0x9}, {0xc00064c130, 0x7}, {0xc0007624e0, 0x24}, {0xc00064c137, 0x7}, ...}, ...})
	/workspace/pkg/inspection/controller.go:225 +0x507
github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection.(*controller).Run.func2.1({0x249b4b8, 0xc00071d880})
	/workspace/pkg/inspection/controller.go:322 +0x399
github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/runtime/grpool.(*pool).Start.func1.2()
	/workspace/pkg/runtime/grpool/pool.go:130 +0x8a
created by github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/runtime/grpool.(*pool).Start.func1
	/workspace/pkg/runtime/grpool/pool.go:120 +0x92
```

**To Reproduce**
1. Enable docker hub replication
2. Do not add label selector for the policy

**Expected behavior and actual behavior:**
At least, the inspector can work properly

**Screenshots**

```
cronjobs        kubefate-policyrt7zn--inspector-27848259-n9pfq             0/1     CrashLoopBackOff   3          99s
```

**Versions:**
not important

**Comment by JingChen23** [comment]
This issue has been resolved in latest release.
